In [1]:
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
b=np.array([(1,2.3,3.45),(4.56,5.34,6.3324),(7,8,9)], dtype = float)
b

array([[1.    , 2.3   , 3.45  ],
       [4.56  , 5.34  , 6.3324],
       [7.    , 8.    , 9.    ]])

In [3]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
zeroArr=np.zeros((3,4), dtype=int)    #Array made up of 0's
zeroArr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
oneArr=np.ones((3,4),dtype=int)       #Array made up of 1's
oneArr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
np.arange(10,250,10)          #1-d array with start, stop(exclusive), step values

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [7]:
np.linspace(0,2,9)         #1-d array with start, stop(inclusive) and range values

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
np.full((3,3),7)          #(n X n)Array filled up of same element

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
np.eye(3,3)               #Identity matrix of (n X n size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.random((3,3))      #(n X n)array made up of random numbers

array([[0.54429405, 0.82238181, 0.43004583],
       [0.52873163, 0.52047179, 0.71370626],
       [0.76945735, 0.08543386, 0.11024228]])

In [11]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.shape     #Array dimensions

(3, 3)

In [15]:
len(a)

3

In [16]:
a.ndim   #Number of array dimensions

2

In [17]:
a.size    #Number of array elements

9

In [18]:
a.dtype.name     #Data type of array elements

'int32'

In [19]:
a.astype(float)    #Convert array to different type

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
b=np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a-b

array([[6., 7., 7.],
       [7., 6., 7.],
       [7., 7., 6.]])

In [23]:
a+b

array([[8., 7., 7.],
       [7., 8., 7.],
       [7., 7., 8.]])

In [24]:
np.multiply(a,b)    #Element wise multiplication

array([[7., 0., 0.],
       [0., 7., 0.],
       [0., 0., 7.]])

In [25]:
np.matmul(a,b)     #Matrix multiplication

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [26]:
np.exp(b)    # e^n, where n is element in array. This is called "Finding the exponential".

array([[2.71828183, 1.        , 1.        ],
       [1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 2.71828183]])

In [27]:
np.sqrt(a)   #Square root of every element in array

array([[2.64575131, 2.64575131, 2.64575131],
       [2.64575131, 2.64575131, 2.64575131],
       [2.64575131, 2.64575131, 2.64575131]])

In [28]:
np.sin(a)   #Sin of every element in array

array([[0.6569866, 0.6569866, 0.6569866],
       [0.6569866, 0.6569866, 0.6569866],
       [0.6569866, 0.6569866, 0.6569866]])

In [29]:
np.cos(b)

array([[0.54030231, 1.        , 1.        ],
       [1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 0.54030231]])

In [30]:
np.log(a)    #Log base e of every element in array

array([[1.94591015, 1.94591015, 1.94591015],
       [1.94591015, 1.94591015, 1.94591015],
       [1.94591015, 1.94591015, 1.94591015]])

In [31]:
a.dot(b)

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [32]:
a==b    #Element wise comparision

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
b>0    #Element wise comparision

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.equal(a,b)    #Element wise comparision

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [35]:
np.array_equal(a,b)    #Array wise comparisions

False

In [36]:
a.sum()     #Sum of all elements

63

In [37]:
a.min()     #Min value in array

7

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
c.max(axis=0)        #Max/Min row(axis=0) or column(axis=1) of an array

array([7, 8, 9])

In [40]:
c.cumsum(axis=1)   #Cumulative sum of elements

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [41]:
c.mean()

5.0

In [42]:
np.median(c)

5.0

In [43]:
np.std(c)     #Standard deviation

2.581988897471611

In [44]:
h=c.view()    #Create a view of array(Changes made to this will alter original array and vice-versa)

In [45]:
i=np.copy(c)    #Create a "DEEP COPY" of array(It's a new array, changes made to this will not  change original array)
i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.copy(c)    #Create a "SHALLOW COPY" of array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
b=np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
b.sort(axis=0)
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [49]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
c[0,1]

2

In [51]:
c[0:2,1]    #Prints element at index 1 in rows 0-1

array([2, 5])

In [52]:
arr=c[:1]
arr

array([[1, 2, 3]])

In [53]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
c[:1][0][0:2]

array([1, 2])

In [55]:
np.flip(c)      #Flip array

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [56]:
c[c<=5]     #Boolean Indexing

array([1, 2, 3, 4, 5])

In [57]:
c[[1,0,1,0],[0,1,2,0]]    #Fancy Indexing(Choose elements(1,0),(0,1),(1,2), and (0,0))

array([4, 2, 6, 1])

In [58]:
i=np.transpose(c)
i

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
i.T   #Another way to transpose

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
b.ravel()   #Flatten the array

array([0., 0., 0., 0., 0., 0., 1., 1., 1.])

In [61]:
h=np.resize(c,(9,1))   #Resize array into m X n dimensions
h

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
np.append(h,[4])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4])

In [63]:
h=np.array([1,2,3,4,5,6,7,8,9])
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.insert(h,h.size,10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.delete(h,[0,2])

array([2, 4, 5, 6, 7, 8, 9])

In [66]:
a1,a2=np.array([1,2,3]), np.array([4,5,6])
a1,a2

(array([1, 2, 3]), array([4, 5, 6]))

In [67]:
np.concatenate((a1,a2),axis=0)

array([1, 2, 3, 4, 5, 6])

In [68]:
np.vstack((a1,a2))    #Another way is np.r_[a1,a2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack((a1,a2))     

array([1, 2, 3, 4, 5, 6])

In [70]:
np.c_[a1,a2]    #Another way is np.column_stack((a1,a2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [71]:
np.hsplit(c,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [72]:
np.vsplit(c,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [73]:
arr1=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
np.vsplit(arr1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]