In [1]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


In [2]:
import tensorflow as tf
import numpy as np
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\ishaan phaye\\AppData\\Roaming\\Python\\Python310\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [3]:
string = tf.Variable("this is a string", tf.string)       #Creating a string, integer and float tensor (Each having rank 0)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.14159265,tf.float16)
print(string.value(), number.value(), floating.value())

tf.Tensor(b'this is a string', shape=(), dtype=string) tf.Tensor(324, shape=(), dtype=int32) tf.Tensor(3.1415927, shape=(), dtype=float32)


In [4]:
rank_1_tensor = tf.Variable(["Jai","Shree","Ram!!!"],tf.string)
rank_1_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'Jai', b'Shree', b'Ram!!!'], dtype=object)>

In [5]:
rank_2_tensor = tf.Variable([["Hello", "Neighbour","is a good game"],["My name is","Ishaan Shailesh Phaye","I'm a proud Hindu!!!"]],tf.string)
rank_2_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'Hello', b'Neighbour', b'is a good game'],
       [b'My name is', b'Ishaan Shailesh Phaye', b"I'm a proud Hindu!!!"]],
      dtype=object)>

In [6]:
tf.rank(rank_2_tensor)       #Shows Rank/Degree of tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
rank_2_tensor.shape        #Shows Shape of tensor(In array form)

TensorShape([2, 3])

In [8]:
tensor1 = tf.ones([1,2,3])     #Creates tensor of 1's of shape (1, 2, 3)
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [9]:
tensor2 = tf.reshape(tensor1,[2,3,1])    #Reshaping tensor, such that number of elements is consistent
tensor3 = tf.reshape(tensor2,[3,2])
tensor2,tensor3

(<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [10]:
matrix = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])     #Making tensor out of a matrix  
tensormat = tf.Variable(matrix,tf.int64)
print(tensormat)
print(tf.rank(tensormat))
print(tensormat.shape)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])>
tf.Tensor(2, shape=(), dtype=int32)
(4, 4)


In [11]:
three = tensormat[0,2]                       
print(three)

row1 = tensormat[0]
print(row1)

column1 = tensormat[:,0]                           #SLICING TENSORS
print(column1)

row_2_and_4 = tensormat[0::2]
print(row_2_and_4)

column_2_and_4 = tensormat[:,::2]
column_2_and_4

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 1  5  9 13], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 9 10 11 12]], shape=(2, 4), dtype=int32)


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])>

In [12]:
tf.ones([1,2,3,4])

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>